security:
  oauth2:
    client:
      clientId: 1038562819623-1ptpdv86b58dm5ns88ukh6h9ukcgggou.apps.googleusercontent.com
      clientSecret: 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
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
      filter-order: 3

server: 
  port: 8080
